---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directory: "/modules"
    schedule:
      interval: "daily"

  # Workaround till https://github.com/dependabot/dependabot-core/issues/2178 is fixed
  - package-ecosystem: "terraform"
    directory: "/modules/azure/analysis_services"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_connectors/key_vault_managed_identity"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_connectors/log_analytics"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_connectors/office365"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_connectors/office365_set"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_connectors/service_bus_managed_identity"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_connectors/storage_blob"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_connectors/storage_blob_managed_identity"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_connectors/storage_table"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_management"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_management_api"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_management_api_operation_policy"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_management_api_simple"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_management_certificate"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_management_custom_domains"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_management_custom_domains_simple"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_management_groups"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_management_logging"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_management_named_values"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/api_management_permissions"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/application_insights"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/application_insights_workbook"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/application_performance_workbook"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/application_role_assignment"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/container_registery"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/data_factory"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/data_factory_blob_to_blob"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/data_factory_http_to_blob"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/data_lake_filesystem"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/data_lake_storage"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/databricks_cluster"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/databricks_permissions"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/databricks_secrets"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/databricks_workspace"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/event_grid_topic"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/event_grid_topic_subscription"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/event_hub"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/frontdoor_classic"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/frontdoor_firewall_policy"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/function_app_linux"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/function_app_linux_managed_identity"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/function_app_windows"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/iam"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/key_vault"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/key_vault_certificate"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/key_vault_secret"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/key_vault_secrets_put"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/key_vault_secrets_put_once"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/log_analytics_diagnostic_setting"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/log_analytics_queries"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/log_analytics_workspace"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/logic_app"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/logic_app_set"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/logic_app_standard"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/logic_app_standard_connection"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/logic_app_standard_connection_access_policy"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/logic_app_trigger_http_request_data"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/maps_account"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/monitoring_action_group"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/monitoring_log_analytics_alert"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/monitoring_metric_alert"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/mssql"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/mysql"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/mysql_flexible_server"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/network_security_group"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/postgresql"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/private_dns_zone"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/public_ip"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/recovery_services_vault"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/resource_group"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/route_table"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/service_bus_public"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/service_bus_subscription"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/service_bus_topic"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/service_plan"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/storage_account_private"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/storage_account_public"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/storage_blob"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/storage_container"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/storage_event_grid"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/storage_queue"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/storage_share"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/storage_table"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/storage_table_entities"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/storage_table_entity"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/stream_analytics"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/subnet"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/synapse_workspace"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/virtual_machine"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/virtual_machine_extension"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/virtual_network"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/virtual_network_peering"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/web_app_linux"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/azure/web_app_windows"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/cloudflare/dns_records"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/elastic/cluster"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/other/local_exec"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/other/password_generator"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/kubernetes/configmap"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/kubernetes/deployment_with_service"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/kubernetes/ingress"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/modules/kubernetes/secret"
    schedule:
      interval: "daily"
