name: "Dummy Code Scanning"

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  code-scanning-dummy:
    name: Perform code scanning (Dummy) - Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
          packs: codeql/javascript-queries

      # Autobuild the language if possible
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
