name: Lint
on:
  push:
    branches:
      - '**'

jobs:
  lint-terraform:
    runs-on: ubuntu-latest
    name: Lint Terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - run: terraform fmt -check -diff -recursive
