name: Validate
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    name: Validate Terraform
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - run: bash ./validate/validate.sh
