name: Validate
on:
  pull_request:
    branches:
      - main
      - develop
      - 4.x

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    name: Validate Terraform
    steps:
      - name: Make space for terragrunt
        run: |
          df -h
          sudo rm -rf "usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - run: bash ./validate/validate.sh
